//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizationResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        internal static string ACCOUNTINFO {
            get {
                return ResourceManager.GetString("ACCOUNTINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dashboard.
        /// </summary>
        internal static string ACS010 {
            get {
                return ResourceManager.GetString("ACS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS020: Request Access for Employee.
        /// </summary>
        internal static string ACS020 {
            get {
                return ResourceManager.GetString("ACS020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS030: Request Access for Visitor.
        /// </summary>
        internal static string ACS030 {
            get {
                return ResourceManager.GetString("ACS030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS040: Request Item Out.
        /// </summary>
        internal static string ACS040 {
            get {
                return ResourceManager.GetString("ACS040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS050: Request Item In.
        /// </summary>
        internal static string ACS050 {
            get {
                return ResourceManager.GetString("ACS050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS060: Request Photographing.
        /// </summary>
        internal static string ACS060 {
            get {
                return ResourceManager.GetString("ACS060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS070: Request Inquiry.
        /// </summary>
        internal static string ACS070 {
            get {
                return ResourceManager.GetString("ACS070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS080: Card Registration.
        /// </summary>
        internal static string ACS080 {
            get {
                return ResourceManager.GetString("ACS080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS081: Receive/Return Card.
        /// </summary>
        internal static string ACS081 {
            get {
                return ResourceManager.GetString("ACS081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS090: VIP Card Registration.
        /// </summary>
        internal static string ACS090 {
            get {
                return ResourceManager.GetString("ACS090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control System.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Registration.
        /// </summary>
        internal static string CARDREGIST {
            get {
                return ResourceManager.GetString("CARDREGIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS010: Miscellaneous.
        /// </summary>
        internal static string MAS010 {
            get {
                return ResourceManager.GetString("MAS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS020: Item Master.
        /// </summary>
        internal static string MAS020 {
            get {
                return ResourceManager.GetString("MAS020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS021: Item Master Entry.
        /// </summary>
        internal static string MAS021 {
            get {
                return ResourceManager.GetString("MAS021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS030: Area Master.
        /// </summary>
        internal static string MAS030 {
            get {
                return ResourceManager.GetString("MAS030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS031: Area Master Entry.
        /// </summary>
        internal static string MAS031 {
            get {
                return ResourceManager.GetString("MAS031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS040: Offline/Online System.
        /// </summary>
        internal static string MAS040 {
            get {
                return ResourceManager.GetString("MAS040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS050: Search Employee.
        /// </summary>
        internal static string MAS050 {
            get {
                return ResourceManager.GetString("MAS050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS051: Employee Entry.
        /// </summary>
        internal static string MAS051 {
            get {
                return ResourceManager.GetString("MAS051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS052: Employee Import.
        /// </summary>
        internal static string MAS052 {
            get {
                return ResourceManager.GetString("MAS052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS060: Card Master.
        /// </summary>
        internal static string MAS060 {
            get {
                return ResourceManager.GetString("MAS060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS061: Card Master Entry.
        /// </summary>
        internal static string MAS061 {
            get {
                return ResourceManager.GetString("MAS061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string MASTER {
            get {
                return ResourceManager.GetString("MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string REQ {
            get {
                return ResourceManager.GetString("REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS010: Log in.
        /// </summary>
        internal static string SYS010 {
            get {
                return ResourceManager.GetString("SYS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS020: User Role.
        /// </summary>
        internal static string SYS020 {
            get {
                return ResourceManager.GetString("SYS020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS030: User Role Authorization.
        /// </summary>
        internal static string SYS030 {
            get {
                return ResourceManager.GetString("SYS030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS040: Change Password.
        /// </summary>
        internal static string SYS040 {
            get {
                return ResourceManager.GetString("SYS040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS050: Schedule Task.
        /// </summary>
        internal static string SYS050 {
            get {
                return ResourceManager.GetString("SYS050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS060: Application Log.
        /// </summary>
        internal static string SYS060 {
            get {
                return ResourceManager.GetString("SYS060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
    }
}
