//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsEmployeeDetail
    {
        public System.Guid DetailID { get; set; }
        public string ReqNo { get; set; }
        public short Seq { get; set; }
        public string EmpID { get; set; }
        public string Name { get; set; }
        public string DeptName { get; set; }
    
        public virtual AcsEmployee AcsEmployee { get; set; }
    }
}
