//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class AcsItemInDetailDataView
    {
        public System.Guid DetailID { get; set; }
        public string ReqNo { get; set; }
        public short Seq { get; set; }
        public int ItemID { get; set; }
        public string Description { get; set; }
        public bool ConfdtFlag { get; set; }
        public int ReqQty { get; set; }
        public Nullable<System.DateTime> PlanReturnDate { get; set; }
        public Nullable<int> ActInQty { get; set; }
        public Nullable<int> ActReturnQty { get; set; }
        public Nullable<System.DateTime> ActReturnDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string ItemDisplayEN { get; set; }
        public string ItemDisplayTH { get; set; }
        public string ItemTypeDisplayEN { get; set; }
        public string ItemTypeDisplayTH { get; set; }
        public int ItemTypeID { get; set; }
    }
}
