//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsItemOut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcsItemOut()
        {
            this.AcsItemOutDetail = new HashSet<AcsItemOutDetail>();
            this.ReqApproverList = new HashSet<ReqApproverList>();
        }
    
        public string ReqNo { get; set; }
        public string Status { get; set; }
        public System.DateTime TakeOutDate { get; set; }
        public int AreaID { get; set; }
        public string Company { get; set; }
        public string DeptName { get; set; }
        public string TakeOutName { get; set; }
        public int PurposeCodeID { get; set; }
        public string OtherPurpose { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string ForceDoneBy { get; set; }
        public Nullable<System.DateTime> ForceDoneDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcsItemOutDetail> AcsItemOutDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqApproverList> ReqApproverList { get; set; }
        public virtual Area Area { get; set; }
    }
}
