//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcsPhoto()
        {
            this.ReqApproverList = new HashSet<ReqApproverList>();
        }
    
        public string ReqNo { get; set; }
        public string Status { get; set; }
        public System.DateTime TakePhotoDateFrom { get; set; }
        public System.TimeSpan TakePhotoTimeFrom { get; set; }
        public System.DateTime TakePhotoDateTo { get; set; }
        public System.TimeSpan TakePhotoTimeTo { get; set; }
        public int AreaID { get; set; }
        public string PhotoByType { get; set; }
        public string PhotoEmpID { get; set; }
        public string TakePhotoName { get; set; }
        public string WitnessEmpID { get; set; }
        public string TargetItem { get; set; }
        public int EquipItemID { get; set; }
        public string OtherEquip { get; set; }
        public int PurposeCodeID { get; set; }
        public string OtherPurpose { get; set; }
        public bool IsLending { get; set; }
        public string AssetCode { get; set; }
        public Nullable<System.DateTime> ActReturnDate { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string AckBy { get; set; }
        public Nullable<System.DateTime> AckDate { get; set; }
        public string ForceDoneBy { get; set; }
        public Nullable<System.DateTime> ForceDoneDate { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqApproverList> ReqApproverList { get; set; }
        public virtual Area Area { get; set; }
    }
}
