//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsTask
    {
        public string TaskID { get; set; }
        public string TaskName { get; set; }
        public bool IsLastResultSuccess { get; set; }
        public string LastResultMessage { get; set; }
        public Nullable<System.DateTime> LastRunDateTime { get; set; }
        public int Success { get; set; }
        public int Fail { get; set; }
        public string UpdateBy { get; set; }
    }
}
