//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcsVisitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcsVisitor()
        {
            this.AcsVisitorDetails = new HashSet<AcsVisitorDetail>();
            this.ReqApproverList = new HashSet<ReqApproverList>();
            this.ReqAreaMappings = new HashSet<ReqAreaMapping>();
            this.TransactionAcs = new HashSet<TransactionAcs>();
        }
    
        public string ReqNo { get; set; }
        public string Status { get; set; }
        public System.DateTime EntryDateFrom { get; set; }
        public System.TimeSpan EntryTimeFrom { get; set; }
        public System.DateTime EntryDateTo { get; set; }
        public System.TimeSpan EntryTimeTo { get; set; }
        public int PurposeCodeID { get; set; }
        public string OtherPurpose { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcsVisitorDetail> AcsVisitorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqApproverList> ReqApproverList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReqAreaMapping> ReqAreaMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionAcs> TransactionAcs { get; set; }
    }
}
