//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaOrganizeMapping
    {
        public System.Guid MappingID { get; set; }
        public string PositionID { get; set; }
        public string DepartmentID { get; set; }
        public string Level { get; set; }
        public int AreaID { get; set; }
        public string SpecialPositionID { get; set; }
    }
}
