//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaApprover
    {
        public int AreaID { get; set; }
        public byte Seq { get; set; }
        public string DepartmentID { get; set; }
        public string PositionID { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Area Area { get; set; }
    }
}
