//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class AreaMapping
    {
        public int AreaID { get; set; }
        public bool IsMainArea { get; set; }
        public string AreaDisplayEN { get; set; }
        public string AreaDisplayTH { get; set; }
        public string EmpID { get; set; }
        public string CardID { get; set; }
        public string FactoryCode { get; set; }
    }
}
