//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaCardMapping
    {
        public string CardID { get; set; }
        public int AreaID { get; set; }
        public bool IsMainArea { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Card Card { get; set; }
    }
}
