//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class CheckOverlapCardNoList
    {
        public System.DateTime EntryDateFrom { get; set; }
        public string CardID { get; set; }
        public string VisitorName { get; set; }
    }
}
