//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class EmployeeApprovalDataView
    {
        public string EmpID { get; set; }
        public string EmpNameEN { get; set; }
        public string EmpNameTH { get; set; }
        public string PositionEN { get; set; }
        public string PositionTH { get; set; }
        public string DepartmentID { get; set; }
        public string PositionID { get; set; }
        public int AreaID { get; set; }
        public string UserName { get; set; }
    }
}
