//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpID { get; set; }
        public string CardID { get; set; }
        public string EmpNameTH { get; set; }
        public string EmpNameEN { get; set; }
        public string Email { get; set; }
        public string DepartmentID { get; set; }
        public string PositionID { get; set; }
        public string Level { get; set; }
        public bool IsHRLink { get; set; }
        public bool IsShow { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartWorkingDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string SpecialPositionID { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
