//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class EmployeeForImportAcs
    {
        public string EmpID { get; set; }
        public string CardNo { get; set; }
        public string CardFormat { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string AccessGroup1 { get; set; }
        public Nullable<System.DateTime> StartGroup1 { get; set; }
        public Nullable<System.DateTime> ExpireGroup1 { get; set; }
        public string AccessGroup2 { get; set; }
        public Nullable<System.DateTime> StartGroup2 { get; set; }
        public Nullable<System.DateTime> ExpireGroup2 { get; set; }
        public string AccessGroup3 { get; set; }
        public Nullable<System.DateTime> StartGroup3 { get; set; }
        public Nullable<System.DateTime> ExpireGroup3 { get; set; }
        public string AccessGroup4 { get; set; }
        public Nullable<System.DateTime> StartGroup4 { get; set; }
        public Nullable<System.DateTime> ExpireGroup4 { get; set; }
        public string AccessGroup5 { get; set; }
        public Nullable<System.DateTime> StartGroup5 { get; set; }
        public Nullable<System.DateTime> ExpireGroup5 { get; set; }
        public string AccessGroup6 { get; set; }
        public Nullable<System.DateTime> StartGroup6 { get; set; }
        public Nullable<System.DateTime> ExpireGroup6 { get; set; }
        public string AccessGroup7 { get; set; }
        public Nullable<System.DateTime> StartGroup7 { get; set; }
        public Nullable<System.DateTime> ExpireGroup7 { get; set; }
        public string AccessGroup8 { get; set; }
        public Nullable<System.DateTime> StartGroup8 { get; set; }
        public Nullable<System.DateTime> ExpireGroup8 { get; set; }
        public string AccessGroup9 { get; set; }
        public Nullable<System.DateTime> StartGroup9 { get; set; }
        public Nullable<System.DateTime> ExpireGroup9 { get; set; }
        public string AccessGroup10 { get; set; }
        public Nullable<System.DateTime> StartGroup10 { get; set; }
        public Nullable<System.DateTime> ExpireGroup10 { get; set; }
        public string AccessGroup11 { get; set; }
        public Nullable<System.DateTime> StartGroup11 { get; set; }
        public Nullable<System.DateTime> ExpireGroup11 { get; set; }
        public string AccessGroup12 { get; set; }
        public Nullable<System.DateTime> StartGroup12 { get; set; }
        public Nullable<System.DateTime> ExpireGroup12 { get; set; }
        public string AccessGroup13 { get; set; }
        public Nullable<System.DateTime> StartGroup13 { get; set; }
        public Nullable<System.DateTime> ExpireGroup13 { get; set; }
        public string AccessGroup14 { get; set; }
        public Nullable<System.DateTime> StartGroup14 { get; set; }
        public Nullable<System.DateTime> ExpireGroup14 { get; set; }
        public string AccessGroup15 { get; set; }
        public Nullable<System.DateTime> StartGroup15 { get; set; }
        public Nullable<System.DateTime> ExpireGroup15 { get; set; }
        public string AccessGroup16 { get; set; }
        public Nullable<System.DateTime> StartGroup16 { get; set; }
        public Nullable<System.DateTime> ExpireGroup16 { get; set; }
        public string AccessGroup17 { get; set; }
        public Nullable<System.DateTime> StartGroup17 { get; set; }
        public Nullable<System.DateTime> ExpireGroup17 { get; set; }
        public string AccessGroup18 { get; set; }
        public Nullable<System.DateTime> StartGroup18 { get; set; }
        public Nullable<System.DateTime> ExpireGroup18 { get; set; }
        public string AccessGroup19 { get; set; }
        public Nullable<System.DateTime> StartGroup19 { get; set; }
        public Nullable<System.DateTime> ExpireGroup19 { get; set; }
        public string AccessGroup20 { get; set; }
        public Nullable<System.DateTime> StartGroup20 { get; set; }
        public Nullable<System.DateTime> ExpireGroup20 { get; set; }
        public string AccessGroup21 { get; set; }
        public Nullable<System.DateTime> StartGroup21 { get; set; }
        public Nullable<System.DateTime> ExpireGroup21 { get; set; }
        public string AccessGroup22 { get; set; }
        public Nullable<System.DateTime> StartGroup22 { get; set; }
        public Nullable<System.DateTime> ExpireGroup22 { get; set; }
        public string AccessGroup23 { get; set; }
        public Nullable<System.DateTime> StartGroup23 { get; set; }
        public Nullable<System.DateTime> ExpireGroup23 { get; set; }
        public string AccessGroup24 { get; set; }
        public Nullable<System.DateTime> StartGroup24 { get; set; }
        public Nullable<System.DateTime> ExpireGroup24 { get; set; }
        public string AccessGroup25 { get; set; }
        public Nullable<System.DateTime> StartGroup25 { get; set; }
        public Nullable<System.DateTime> ExpireGroup25 { get; set; }
        public string AccessGroup26 { get; set; }
        public Nullable<System.DateTime> StartGroup26 { get; set; }
        public Nullable<System.DateTime> ExpireGroup26 { get; set; }
        public string AccessGroup27 { get; set; }
        public Nullable<System.DateTime> StartGroup27 { get; set; }
        public Nullable<System.DateTime> ExpireGroup27 { get; set; }
        public string AccessGroup28 { get; set; }
        public Nullable<System.DateTime> StartGroup28 { get; set; }
        public Nullable<System.DateTime> ExpireGroup28 { get; set; }
        public string AccessGroup29 { get; set; }
        public Nullable<System.DateTime> StartGroup29 { get; set; }
        public Nullable<System.DateTime> ExpireGroup29 { get; set; }
        public string AccessGroup30 { get; set; }
        public Nullable<System.DateTime> StartGroup30 { get; set; }
        public Nullable<System.DateTime> ExpireGroup30 { get; set; }
        public string AccessGroup31 { get; set; }
        public Nullable<System.DateTime> StartGroup31 { get; set; }
        public Nullable<System.DateTime> ExpireGroup31 { get; set; }
        public string AccessGroup32 { get; set; }
        public Nullable<System.DateTime> StartGroup32 { get; set; }
        public Nullable<System.DateTime> ExpireGroup32 { get; set; }
        public string AccessGroup33 { get; set; }
        public Nullable<System.DateTime> StartGroup33 { get; set; }
        public Nullable<System.DateTime> ExpireGroup33 { get; set; }
        public string AccessGroup34 { get; set; }
        public Nullable<System.DateTime> StartGroup34 { get; set; }
        public Nullable<System.DateTime> ExpireGroup34 { get; set; }
        public string AccessGroup35 { get; set; }
        public Nullable<System.DateTime> StartGroup35 { get; set; }
        public Nullable<System.DateTime> ExpireGroup35 { get; set; }
        public string AccessGroup36 { get; set; }
        public Nullable<System.DateTime> StartGroup36 { get; set; }
        public Nullable<System.DateTime> ExpireGroup36 { get; set; }
        public string AccessGroup37 { get; set; }
        public Nullable<System.DateTime> StartGroup37 { get; set; }
        public Nullable<System.DateTime> ExpireGroup37 { get; set; }
        public string AccessGroup38 { get; set; }
        public Nullable<System.DateTime> StartGroup38 { get; set; }
        public Nullable<System.DateTime> ExpireGroup38 { get; set; }
        public string AccessGroup39 { get; set; }
        public Nullable<System.DateTime> StartGroup39 { get; set; }
        public Nullable<System.DateTime> ExpireGroup39 { get; set; }
        public string AccessGroup40 { get; set; }
        public Nullable<System.DateTime> StartGroup40 { get; set; }
        public Nullable<System.DateTime> ExpireGroup40 { get; set; }
        public string AccessGroup41 { get; set; }
        public Nullable<System.DateTime> StartGroup41 { get; set; }
        public Nullable<System.DateTime> ExpireGroup41 { get; set; }
        public string AccessGroup42 { get; set; }
        public Nullable<System.DateTime> StartGroup42 { get; set; }
        public Nullable<System.DateTime> ExpireGroup42 { get; set; }
        public string AccessGroup43 { get; set; }
        public Nullable<System.DateTime> StartGroup43 { get; set; }
        public Nullable<System.DateTime> ExpireGroup43 { get; set; }
        public string AccessGroup44 { get; set; }
        public Nullable<System.DateTime> StartGroup44 { get; set; }
        public Nullable<System.DateTime> ExpireGroup44 { get; set; }
        public string AccessGroup45 { get; set; }
        public Nullable<System.DateTime> StartGroup45 { get; set; }
        public Nullable<System.DateTime> ExpireGroup45 { get; set; }
        public string AccessGroup46 { get; set; }
        public Nullable<System.DateTime> StartGroup46 { get; set; }
        public Nullable<System.DateTime> ExpireGroup46 { get; set; }
        public string AccessGroup47 { get; set; }
        public Nullable<System.DateTime> StartGroup47 { get; set; }
        public Nullable<System.DateTime> ExpireGroup47 { get; set; }
        public string AccessGroup48 { get; set; }
        public Nullable<System.DateTime> StartGroup48 { get; set; }
        public Nullable<System.DateTime> ExpireGroup48 { get; set; }
        public string AccessGroup49 { get; set; }
        public Nullable<System.DateTime> StartGroup49 { get; set; }
        public Nullable<System.DateTime> ExpireGroup49 { get; set; }
        public string AccessGroup50 { get; set; }
        public Nullable<System.DateTime> StartGroup50 { get; set; }
        public Nullable<System.DateTime> ExpireGroup50 { get; set; }
    }
}
