//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misc
    {
        public int MiscID { get; set; }
        public string MiscType { get; set; }
        public string MiscName { get; set; }
        public string MiscDisplayEN { get; set; }
        public string MiscDisplayTH { get; set; }
        public string MiscRemark { get; set; }
        public bool IsActive { get; set; }
        public bool DeleteAble { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
