//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class PrivilegeViewDSHData
    {
        public bool ViewDSH01 { get; set; }
        public bool ViewDSH02 { get; set; }
        public bool ViewDSH03 { get; set; }
        public bool ViewDSH04 { get; set; }
        public bool ViewDSH05 { get; set; }
        public bool ViewDSH06 { get; set; }
        public bool ViewDSH07 { get; set; }
        public bool ViewDSH08 { get; set; }
        public bool ViewDSH09 { get; set; }
        public bool IsVerifyItemIn { get; set; }
        public bool IsVerifyItemOut { get; set; }
        public bool IsLending { get; set; }
    }
}
