//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqApproverList
    {
        public string ReqNo { get; set; }
        public string ReqType { get; set; }
        public byte Step { get; set; }
        public string ApproveUserName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string RejectReason { get; set; }
        public System.Guid ApprovalID { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> ReferenceApprovalID { get; set; }
    
        public virtual AcsItemOut AcsItemOut { get; set; }
        public virtual AcsPhoto AcsPhoto { get; set; }
        public virtual AcsVisitor AcsVisitor { get; set; }
        public virtual AcsVIP AcsVIP { get; set; }
        public virtual AcsEmployee AcsEmployee { get; set; }
        public virtual AcsItemIn AcsItemIn { get; set; }
    }
}
