//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqAreaMapping
    {
        public string ReqNo { get; set; }
        public string ReqType { get; set; }
        public int AreaID { get; set; }
    
        public virtual AcsVisitor AcsVisitor { get; set; }
        public virtual AcsVIP AcsVIP { get; set; }
        public virtual AcsEmployee AcsEmployee { get; set; }
        public virtual Area Area { get; set; }
    }
}
