//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMisc
    {
        public string SysMiscType { get; set; }
        public string SysMiscCode { get; set; }
        public string SysMiscValue1 { get; set; }
        public string SysMiscValue2 { get; set; }
        public string SysMiscValue3 { get; set; }
        public Nullable<int> SysMiscSortNo { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
