//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAcs
    {
        public System.Guid TranID { get; set; }
        public string ReqNo { get; set; }
        public string ReqType { get; set; }
        public System.Guid DetailID { get; set; }
        public System.DateTime EntryDateFrom { get; set; }
        public System.TimeSpan EntryTimeFrom { get; set; }
        public System.DateTime EntryDateTo { get; set; }
        public System.TimeSpan EntryTimeTo { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> CardReceiveTime { get; set; }
        public Nullable<System.DateTime> CardReturnTime { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> SendAcsDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> CancelAcsDate { get; set; }
    
        public virtual AcsVisitor AcsVisitor { get; set; }
        public virtual AcsVIP AcsVIP { get; set; }
        public virtual AcsEmployee AcsEmployee { get; set; }
    }
}
