//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.Models
{
    using System;
    
    public partial class VIPCardRegistrationView
    {
        public string CardNo { get; set; }
        public string CardID { get; set; }
        public string ReqNo { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> EntryDateFrom { get; set; }
        public Nullable<System.DateTime> EntryDateTo { get; set; }
        public string Description { get; set; }
        public Nullable<int> PositionMiscID { get; set; }
        public string AreaID { get; set; }
        public string StatusEN { get; set; }
        public string StatusTH { get; set; }
        public string Status { get; set; }
    }
}
