//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsEmployeeDetailViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsEmployeeDetailViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsEmployeeDetailViewModelResource", typeof(AcsEmployeeDetailViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_Department {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_DepartmentName {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_EmployeeID {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_EmployeeName {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string AcsEmployeeDetailViewModel_RequestNo {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_Seq {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type.
        /// </summary>
        public static string AcsEmployeeDetailViewModel_VerifyTypeID {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailViewModel_VerifyTypeID", resourceCulture);
            }
        }
    }
}
