//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsItemInViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsItemInViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsItemInViewModelResource", typeof(AcsItemInViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsItemInViewModel_AcknowledgeDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AcknowledgeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string AcsItemInViewModel_AcknowledgeUserName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AcknowledgeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Detail.
        /// </summary>
        public static string AcsItemInViewModel_AcsItemInDetails {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AcsItemInDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemInViewModel_AreaApprovalCode {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AreaApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsItemInViewModel_AreaApprovalDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AreaApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AcsItemInViewModel_AreaApproveUserName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AreaApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bringing Area.
        /// </summary>
        public static string AcsItemInViewModel_AreaID {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsItemInViewModel_AreaRejectReason {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_AreaRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string AcsItemInViewModel_Company {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string AcsItemInViewModel_CreateBy {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string AcsItemInViewModel_CreateDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string AcsItemInViewModel_DeptName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceDoneBy.
        /// </summary>
        public static string AcsItemInViewModel_ForceDoneBy {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_ForceDoneBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceDoneDate.
        /// </summary>
        public static string AcsItemInViewModel_ForceDoneDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_ForceDoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Purpose.
        /// </summary>
        public static string AcsItemInViewModel_OtherPurpose {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_OtherPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string AcsItemInViewModel_PurposeCodeID {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_PurposeCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No.
        /// </summary>
        public static string AcsItemInViewModel_ReqNo {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string AcsItemInViewModel_RequestEmployeeDepartmentName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_RequestEmployeeDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeName.
        /// </summary>
        public static string AcsItemInViewModel_RequestEmployeeName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_RequestEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string AcsItemInViewModel_RequestStatus {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemInViewModel_Status {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemInViewModel_SuperiorApprovalCode {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_SuperiorApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsItemInViewModel_SuperiorApprovalDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_SuperiorApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string AcsItemInViewModel_SuperiorApproveUserName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_SuperiorApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsItemInViewModel_SuperiorRejectReason {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_SuperiorRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Company.
        /// </summary>
        public static string AcsItemInViewModel_TakeInCompany {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_TakeInCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Date.
        /// </summary>
        public static string AcsItemInViewModel_TakeInDate {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_TakeInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Department.
        /// </summary>
        public static string AcsItemInViewModel_TakeInDept {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_TakeInDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Name.
        /// </summary>
        public static string AcsItemInViewModel_TakeInName {
            get {
                return ResourceManager.GetString("AcsItemInViewModel_TakeInName", resourceCulture);
            }
        }
    }
}
