//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsItemOutItemViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsItemOutItemViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsItemOutItemViewModelResource", typeof(AcsItemOutItemViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act. Return Date.
        /// </summary>
        public static string AcsItemOutItemViewModel_ActualReturn {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ActualReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act. Return Qty..
        /// </summary>
        public static string AcsItemOutItemViewModel_ActualReturnQty {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ActualReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act. Take Out Qty..
        /// </summary>
        public static string AcsItemOutItemViewModel_ActualTakeOutQty {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ActualTakeOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        public static string AcsItemOutItemViewModel_Confidential {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_Confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AcsItemOutItemViewModel_Description {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string AcsItemOutItemViewModel_ItemID {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string AcsItemOutItemViewModel_ItemName {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AcsItemOutItemViewModel_ItemTypeID {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ItemTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AcsItemOutItemViewModel_ItemTypeName {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_ItemTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Return Date.
        /// </summary>
        public static string AcsItemOutItemViewModel_PlanReturnDate {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_PlanReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Qty..
        /// </summary>
        public static string AcsItemOutItemViewModel_RequestItemQty {
            get {
                return ResourceManager.GetString("AcsItemOutItemViewModel_RequestItemQty", resourceCulture);
            }
        }
    }
}
