//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsItemOutViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsItemOutViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsItemOutViewModelResource", typeof(AcsItemOutViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Area.
        /// </summary>
        public static string AcsItemOutViewModel_Area {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Area.
        /// </summary>
        public static string AcsItemOutViewModel_AreaID {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string AcsItemOutViewModel_Company {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string AcsItemOutViewModel_CreateBy {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string AcsItemOutViewModel_CreateDate {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department/Shop.
        /// </summary>
        public static string AcsItemOutViewModel_Department {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Done.
        /// </summary>
        public static string AcsItemOutViewModel_ForceDoneBy {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_ForceDoneBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Done Date.
        /// </summary>
        public static string AcsItemOutViewModel_ForceDoneDate {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_ForceDoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemOutViewModel_GAApprovalCode {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_GAApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string AcsItemOutViewModel_GAApprovalDate {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_GAApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA.
        /// </summary>
        public static string AcsItemOutViewModel_GAApproveUserName {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_GAApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsItemOutViewModel_GARejectReason {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_GARejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Purpose.
        /// </summary>
        public static string AcsItemOutViewModel_OtherPurpose {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_OtherPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string AcsItemOutViewModel_PurposeCodeID {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_PurposeCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No.
        /// </summary>
        public static string AcsItemOutViewModel_RequestNo {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string AcsItemOutViewModel_RequestStatus {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemOutViewModel_Status {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsItemOutViewModel_SuperiorApprovalCode {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_SuperiorApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string AcsItemOutViewModel_SuperiorApprovalDate {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_SuperiorApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string AcsItemOutViewModel_SuperiorApproveUserName {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_SuperiorApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsItemOutViewModel_SuperiorRejectReason {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_SuperiorRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Out Date.
        /// </summary>
        public static string AcsItemOutViewModel_TakeOutDate {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_TakeOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Name.
        /// </summary>
        public static string AcsItemOutViewModel_TakeOutName {
            get {
                return ResourceManager.GetString("AcsItemOutViewModel_TakeOutName", resourceCulture);
            }
        }
    }
}
