//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsPhotoViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsPhotoViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsPhotoViewModelResource", typeof(AcsPhotoViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsPhotoViewModel_AcknowledgeDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AcknowledgeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string AcsPhotoViewModel_AcknowledgeUserName {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AcknowledgeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Return Date.
        /// </summary>
        public static string AcsPhotoViewModel_ActReturnDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_ActReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsPhotoViewModel_AreaApprovalCode {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AreaApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsPhotoViewModel_AreaApprovalDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AreaApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AcsPhotoViewModel_AreaApproveUserName {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AreaApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AcsPhotoViewModel_AreaID {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsPhotoViewModel_AreaRejectReason {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AreaRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Code.
        /// </summary>
        public static string AcsPhotoViewModel_AssetCode {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string AcsPhotoViewModel_CreateBy {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string AcsPhotoViewModel_CreateDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string AcsPhotoViewModel_EquipItemID {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_EquipItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Done By.
        /// </summary>
        public static string AcsPhotoViewModel_ForceDoneBy {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_ForceDoneBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Done Date.
        /// </summary>
        public static string AcsPhotoViewModel_ForceDoneDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_ForceDoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Lending.
        /// </summary>
        public static string AcsPhotoViewModel_IsLending {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_IsLending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string AcsPhotoViewModel_Note {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Equipment.
        /// </summary>
        public static string AcsPhotoViewModel_OtherEquip {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_OtherEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Purpose.
        /// </summary>
        public static string AcsPhotoViewModel_OtherPurpose {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_OtherPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo By Type.
        /// </summary>
        public static string AcsPhotoViewModel_PhotoByType {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_PhotoByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Employee.
        /// </summary>
        public static string AcsPhotoViewModel_PhotoEmpID {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_PhotoEmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string AcsPhotoViewModel_PurposeCodeID {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_PurposeCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string AcsPhotoViewModel_ReqNo {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string AcsPhotoViewModel_RequestEmployeeDepartmentName {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_RequestEmployeeDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsPhotoViewModel_Status {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsPhotoViewModel_SuperiorApprovalCode {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_SuperiorApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AcsPhotoViewModel_SuperiorApprovalDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_SuperiorApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string AcsPhotoViewModel_SuperiorApproveUserName {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_SuperiorApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsPhotoViewModel_SuperiorRejectReason {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_SuperiorRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo Date.
        /// </summary>
        public static string AcsPhotoViewModel_TakePhotoDateFrom {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_TakePhotoDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo Name.
        /// </summary>
        public static string AcsPhotoViewModel_TakePhotoName {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_TakePhotoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Item.
        /// </summary>
        public static string AcsPhotoViewModel_TargetItem {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_TargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string AcsPhotoViewModel_UpdateBy {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string AcsPhotoViewModel_UpdateDate {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Employee.
        /// </summary>
        public static string AcsPhotoViewModel_WitnessEmpID {
            get {
                return ResourceManager.GetString("AcsPhotoViewModel_WitnessEmpID", resourceCulture);
            }
        }
    }
}
