//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsTransactionViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsTransactionViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsTransactionViewModelResource", typeof(AcsTransactionViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Acs Date.
        /// </summary>
        public static string AcsTransactionViewModel_CancelAcsDate {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_CancelAcsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        public static string AcsTransactionViewModel_CardID {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Receive Time.
        /// </summary>
        public static string AcsTransactionViewModel_CardReceiveTime {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_CardReceiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Return Time.
        /// </summary>
        public static string AcsTransactionViewModel_CardReturnTime {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_CardReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date From.
        /// </summary>
        public static string AcsTransactionViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date To.
        /// </summary>
        public static string AcsTransactionViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time From.
        /// </summary>
        public static string AcsTransactionViewModel_EntryTimeFrom {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_EntryTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time To.
        /// </summary>
        public static string AcsTransactionViewModel_EntryTimeTo {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_EntryTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string AcsTransactionViewModel_ReqNo {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string AcsTransactionViewModel_ReqType {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_ReqType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Acs Date.
        /// </summary>
        public static string AcsTransactionViewModel_SendAcsDate {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_SendAcsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsTransactionViewModel_Status {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string AcsTransactionViewModel_UpdateBy {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string AcsTransactionViewModel_UpdateDate {
            get {
                return ResourceManager.GetString("AcsTransactionViewModel_UpdateDate", resourceCulture);
            }
        }
    }
}
