//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsVisitorViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsVisitorViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsVisitorViewModelResource", typeof(AcsVisitorViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor List.
        /// </summary>
        public static string AcsVisitorViewModel_AcsVisitorDetails {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_AcsVisitorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Approver.
        /// </summary>
        public static string AcsVisitorViewModel_AreaApproveUserName {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_AreaApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AcsVisitorViewModel_Areas {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string AcsVisitorViewModel_CreateBy {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string AcsVisitorViewModel_CreateDate {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date From.
        /// </summary>
        public static string AcsVisitorViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date To.
        /// </summary>
        public static string AcsVisitorViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time From.
        /// </summary>
        public static string AcsVisitorViewModel_EntryTimeFrom {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_EntryTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time To.
        /// </summary>
        public static string AcsVisitorViewModel_EntryTimeTo {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_EntryTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string AcsVisitorViewModel_Note {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string AcsVisitorViewModel_OtherPurpose {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_OtherPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string AcsVisitorViewModel_PurposeCodeID {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_PurposeCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string AcsVisitorViewModel_ReqNo {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsVisitorViewModel_Status {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AcsVisitorViewModel_SuperiorApprovalCode {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_SuperiorApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string AcsVisitorViewModel_SuperiorApprovalDate {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_SuperiorApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string AcsVisitorViewModel_SuperiorApproveUserName {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_SuperiorApproveUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string AcsVisitorViewModel_SuperiorRejectReason {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_SuperiorRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string AcsVisitorViewModel_UpdateBy {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string AcsVisitorViewModel_UpdateDate {
            get {
                return ResourceManager.GetString("AcsVisitorViewModel_UpdateDate", resourceCulture);
            }
        }
    }
}
