//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsVisitorDetailViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsVisitorDetailViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsVisitorDetailViewModelResource", typeof(AcsVisitorDetailViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string AcsVisitorDetailViewModel_Company {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string AcsVisitorDetailViewModel_DepartmentName {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AcsVisitorDetailViewModel_Description {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemInOut.
        /// </summary>
        public static string AcsVisitorDetailViewModel_ItemInOut {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_ItemInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographing.
        /// </summary>
        public static string AcsVisitorDetailViewModel_Photographing {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_Photographing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string AcsVisitorDetailViewModel_RequestNo {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq.
        /// </summary>
        public static string AcsVisitorDetailViewModel_Seq {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify No..
        /// </summary>
        public static string AcsVisitorDetailViewModel_VerifyNo {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_VerifyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type.
        /// </summary>
        public static string AcsVisitorDetailViewModel_VerifyTypeID {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_VerifyTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Name.
        /// </summary>
        public static string AcsVisitorDetailViewModel_VisitorName {
            get {
                return ResourceManager.GetString("AcsVisitorDetailViewModel_VisitorName", resourceCulture);
            }
        }
    }
}
