//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AcsVisitorTransactionDataViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcsVisitorTransactionDataViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AcsVisitorTransactionDataViewModelResource", typeof(AcsVisitorTransactionDataViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardID.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_CardID {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNo.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_CardNo {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_Company {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_DepartmentName {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date From.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date To.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time From.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_EntryTimeFrom {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_EntryTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time To.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_EntryTimeTo {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_EntryTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_Name {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type ID.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_VerifyTypeID {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_VerifyTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type Name.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_VerifyTypeName {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_VerifyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type No.
        /// </summary>
        public static string AcsVisitorTransactionDataViewModel_VerifyTypeNo {
            get {
                return ResourceManager.GetString("AcsVisitorTransactionDataViewModel_VerifyTypeNo", resourceCulture);
            }
        }
    }
}
