//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AreaForEmployeeEntryViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AreaForEmployeeEntryViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.AreaForEmployeeEntryViewModelResource", typeof(AreaForEmployeeEntryViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaID.
        /// </summary>
        public static string AreaMappingViewModel_AreaID {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaName.
        /// </summary>
        public static string AreaMappingViewModel_AreaName {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoryCode.
        /// </summary>
        public static string AreaMappingViewModel_FactoryCode {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_FactoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AreaMappingViewModel_ID {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMainArea.
        /// </summary>
        public static string AreaMappingViewModel_IsMainArea {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_IsMainArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AreaMappingViewModel_Name {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_Name", resourceCulture);
            }
        }
    }
}
