//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessTripCardRegistrationViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessTripCardRegistrationViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.BusinessTripCardRegistrationViewModelResource", typeof(BusinessTripCardRegistrationViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_AreaName {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Employee Name.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_BusinessEmployeeName {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_BusinessEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_CardID {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_CardNo {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail ID.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_DetailID {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_DetailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester name.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_EmployeeName {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryDate From.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntryDate To.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tran ID.
        /// </summary>
        public static string BusinessTripCardRegistrationViewModel_TranID {
            get {
                return ResourceManager.GetString("BusinessTripCardRegistrationViewModel_TranID", resourceCulture);
            }
        }
    }
}
