//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeDataViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeDataViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.EmployeeDataViewModelResource", typeof(EmployeeDataViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaID.
        /// </summary>
        public static string EmployeeDataViewModel_AreaID {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentID.
        /// </summary>
        public static string EmployeeDataViewModel_DepartmentID {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string EmployeeDataViewModel_DepartmentName {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeDataViewModel_EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeDataViewModel_EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionID.
        /// </summary>
        public static string EmployeeDataViewModel_PositionID {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_PositionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string EmployeeDataViewModel_PositionName {
            get {
                return ResourceManager.GetString("EmployeeDataViewModel_PositionName", resourceCulture);
            }
        }
    }
}
