//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to cancel this request?.
        /// </summary>
        public static string ConfirmCancelRequest {
            get {
                return ResourceManager.GetString("ConfirmCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to clear employee list?.
        /// </summary>
        public static string ConfirmClearEmployeeList {
            get {
                return ResourceManager.GetString("ConfirmClearEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to clear visitor list?.
        /// </summary>
        public static string ConfirmClearVisitorList {
            get {
                return ResourceManager.GetString("ConfirmClearVisitorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to acknowledge thils request?.
        /// </summary>
        public static string ConfirmGAAcknowledge {
            get {
                return ResourceManager.GetString("ConfirmGAAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to receive card?.
        /// </summary>
        public static string ConfirmReceiveCard {
            get {
                return ResourceManager.GetString("ConfirmReceiveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to reset password ?.
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to return card?.
        /// </summary>
        public static string ConfirmReturnCard {
            get {
                return ResourceManager.GetString("ConfirmReturnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to run batch process?.
        /// </summary>
        public static string ConfirmRunTask {
            get {
                return ResourceManager.GetString("ConfirmRunTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution: Could not add or update area when employee card id not found..
        /// </summary>
        public static string CouldNotUpdateUserAreaMappingWhenCardIDNotFound {
            get {
                return ResourceManager.GetString("CouldNotUpdateUserAreaMappingWhenCardIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution: Could not add or update user group when employee does not map with user data..
        /// </summary>
        public static string CouldNotUpdateUserRoleMappingWhenUserNameNotFound {
            get {
                return ResourceManager.GetString("CouldNotUpdateUserRoleMappingWhenUserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input {0} . Date must be less than or equal {1}..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request approval data. Request approval data not found.
        /// </summary>
        public static string InvalidReqApprovalRequest {
            get {
                return ResourceManager.GetString("InvalidReqApprovalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request status to cancel request..
        /// </summary>
        public static string InvalidRequestStatusForCancelRequest {
            get {
                return ResourceManager.GetString("InvalidRequestStatusForCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register data in suspend service time..
        /// </summary>
        public static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a permission to operate requested screen..
        /// </summary>
        public static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this data?.
        /// </summary>
        public static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completely..
        /// </summary>
        public static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this data.
        ///{0}.
        /// </summary>
        public static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save?.
        /// </summary>
        public static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save completely..
        /// </summary>
        public static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel?.
        /// </summary>
        public static string MSG0009 {
            get {
                return ResourceManager.GetString("MSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string MSG0010 {
            get {
                return ResourceManager.GetString("MSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is duplicate: {1}..
        /// </summary>
        public static string MSG0011 {
            get {
                return ResourceManager.GetString("MSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Employee ID from MAS050.
        /// </summary>
        public static string MSG0012 {
            get {
                return ResourceManager.GetString("MSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select data in {0} dropdown list.
        /// </summary>
        public static string MSG0013 {
            get {
                return ResourceManager.GetString("MSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset?.
        /// </summary>
        public static string MSG0014 {
            get {
                return ResourceManager.GetString("MSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are duplicate: {2} {3}..
        /// </summary>
        public static string MSG0015 {
            get {
                return ResourceManager.GetString("MSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this data.
        ///{0} data is in use..
        /// </summary>
        public static string MSG0016 {
            get {
                return ResourceManager.GetString("MSG0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this data.
        ///{0} : {1} data is in use..
        /// </summary>
        public static string MSG0017 {
            get {
                return ResourceManager.GetString("MSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of range..
        /// </summary>
        public static string MSG0018 {
            get {
                return ResourceManager.GetString("MSG0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request require superior approval; But there is not superior data found. 
        ///Please contact HR or System Admin to set up your seperior..
        /// </summary>
        public static string MSG0019 {
            get {
                return ResourceManager.GetString("MSG0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reject?.
        /// </summary>
        public static string MSG0020 {
            get {
                return ResourceManager.GetString("MSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to approve?.
        /// </summary>
        public static string MSG0021 {
            get {
                return ResourceManager.GetString("MSG0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to force the request status to be done?.
        /// </summary>
        public static string MSG0022 {
            get {
                return ResourceManager.GetString("MSG0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to acknowledge?.
        /// </summary>
        public static string MSG0023 {
            get {
                return ResourceManager.GetString("MSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not data for sent to ACS Control System.
        /// </summary>
        public static string MSG0024 {
            get {
                return ResourceManager.GetString("MSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;After you change &apos;Request For&apos; type, all input item in Employee List section will be deleted.
        ///Are you sure to change &apos;Request For&apos;?&quot;.
        /// </summary>
        public static string MSG0025 {
            get {
                return ResourceManager.GetString("MSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicate {0} In list..
        /// </summary>
        public static string MSG0031 {
            get {
                return ResourceManager.GetString("MSG0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No. {0} used by {1} in same day..
        /// </summary>
        public static string MSG0032 {
            get {
                return ResourceManager.GetString("MSG0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are duplicate employee {0} on employee list..
        /// </summary>
        public static string MSG0033 {
            get {
                return ResourceManager.GetString("MSG0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Please input data in English only..
        /// </summary>
        public static string MSG0034 {
            get {
                return ResourceManager.GetString("MSG0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Please input data in English only..
        /// </summary>
        public static string MSG0035 {
            get {
                return ResourceManager.GetString("MSG0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Please input data in English only..
        /// </summary>
        public static string MSG0036 {
            get {
                return ResourceManager.GetString("MSG0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Please input data in English only..
        /// </summary>
        public static string MSG0037 {
            get {
                return ResourceManager.GetString("MSG0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Please input data in English only..
        /// </summary>
        public static string MSG0038 {
            get {
                return ResourceManager.GetString("MSG0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Caution *** Don&apos;t use mobile or small camera to take a photo..
        /// </summary>
        public static string MSG0039 {
            get {
                return ResourceManager.GetString("MSG0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is being referenced..
        /// </summary>
        public static string MSG0040 {
            get {
                return ResourceManager.GetString("MSG0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSG0041: Application&apos;s session is timeout..
        /// </summary>
        public static string MSG0041 {
            get {
                return ResourceManager.GetString("MSG0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is reset. System send new password to your email. Please check your email to see new password..
        /// </summary>
        public static string PasswordResetCompleted {
            get {
                return ResourceManager.GetString("PasswordResetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length requirement is {0}.
        /// </summary>
        public static string PasswordValidator_MinimumPasswordLength {
            get {
                return ResourceManager.GetString("PasswordValidator_MinimumPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When change schedule task time, It will not effective to new schedule time until service is restart. To restart service click [Restart Service] button at toolbar in grid..
        /// </summary>
        public static string ScheduleTask_RequiredRestart {
            get {
                return ResourceManager.GetString("ScheduleTask_RequiredRestart", resourceCulture);
            }
        }
    }
}
