//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelMetadataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelMetadataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.ModelMetadataResource", typeof(ModelMetadataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AccountViewModel_Email {
            get {
                return ResourceManager.GetString("AccountViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string AccountViewModel_EmployeeID {
            get {
                return ResourceManager.GetString("AccountViewModel_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Code.
        /// </summary>
        public static string AccountViewModel_FactoryCode {
            get {
                return ResourceManager.GetString("AccountViewModel_FactoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AccountViewModel_IsActive {
            get {
                return ResourceManager.GetString("AccountViewModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Signed In Date.
        /// </summary>
        public static string AccountViewModel_LastSignedInDateTime {
            get {
                return ResourceManager.GetString("AccountViewModel_LastSignedInDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Date.
        /// </summary>
        public static string AccountViewModel_RegisteredDateTime {
            get {
                return ResourceManager.GetString("AccountViewModel_RegisteredDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AccountViewModel_Roles {
            get {
                return ResourceManager.GetString("AccountViewModel_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AccountViewModel_Username {
            get {
                return ResourceManager.GetString("AccountViewModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string Acknowledged_Status {
            get {
                return ResourceManager.GetString("Acknowledged_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for approval..
        /// </summary>
        public static string ApprovalCode_WaitApproval {
            get {
                return ResourceManager.GetString("ApprovalCode_WaitApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        public static string AreaMappingViewModel_AreaName {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Area.
        /// </summary>
        public static string AreaMappingViewModel_IsMainArea {
            get {
                return ResourceManager.GetString("AreaMappingViewModel_IsMainArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string AreaStatus_Active {
            get {
                return ResourceManager.GetString("AreaStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string AreaStatus_Inactive {
            get {
                return ResourceManager.GetString("AreaStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Display Name (EN).
        /// </summary>
        public static string AreaViewModel_AreaDisplayEN {
            get {
                return ResourceManager.GetString("AreaViewModel_AreaDisplayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Display Name (TH).
        /// </summary>
        public static string AreaViewModel_AreaDisplayTH {
            get {
                return ResourceManager.GetString("AreaViewModel_AreaDisplayTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area ID.
        /// </summary>
        public static string AreaViewModel_AreaID {
            get {
                return ResourceManager.GetString("AreaViewModel_AreaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        public static string AreaViewModel_AreaName {
            get {
                return ResourceManager.GetString("AreaViewModel_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential Level.
        /// </summary>
        public static string AreaViewModel_ConfdtLevel {
            get {
                return ResourceManager.GetString("AreaViewModel_ConfdtLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string AreaViewModel_FactoryCode {
            get {
                return ResourceManager.GetString("AreaViewModel_FactoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gates.
        /// </summary>
        public static string AreaViewModel_Gates {
            get {
                return ResourceManager.GetString("AreaViewModel_Gates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AreaViewModel_Status {
            get {
                return ResourceManager.GetString("AreaViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string CardStatus_Active {
            get {
                return ResourceManager.GetString("CardStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        public static string CardStatus_Inactive {
            get {
                return ResourceManager.GetString("CardStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string CardViewModel_Area {
            get {
                return ResourceManager.GetString("CardViewModel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        public static string CardViewModel_CardID {
            get {
                return ResourceManager.GetString("CardViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string CardViewModel_CardNo {
            get {
                return ResourceManager.GetString("CardViewModel_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string CardViewModel_CardType {
            get {
                return ResourceManager.GetString("CardViewModel_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CardViewModel_IsActive {
            get {
                return ResourceManager.GetString("CardViewModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string CardViewModel_Note {
            get {
                return ResourceManager.GetString("CardViewModel_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ChangePasswordViewModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ChangePasswordViewModel_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ChangePasswordViewModel_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePasswordViewModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must not equal current password..
        /// </summary>
        public static string ChangePasswordViewModel_NewPassword_Compare {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_NewPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ItemDataViewModel_Description {
            get {
                return ResourceManager.GetString("ItemDataViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ItemDataViewModel_IsActive {
            get {
                return ResourceManager.GetString("ItemDataViewModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        public static string ItemDataViewModel_IsConfdt {
            get {
                return ResourceManager.GetString("ItemDataViewModel_IsConfdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item In.
        /// </summary>
        public static string ItemDataViewModel_IsItemIn {
            get {
                return ResourceManager.GetString("ItemDataViewModel_IsItemIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Out.
        /// </summary>
        public static string ItemDataViewModel_IsItemOut {
            get {
                return ResourceManager.GetString("ItemDataViewModel_IsItemOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string ItemDataViewModel_IsPhoto {
            get {
                return ResourceManager.GetString("ItemDataViewModel_IsPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name (EN).
        /// </summary>
        public static string ItemDataViewModel_ItemDisplayEN {
            get {
                return ResourceManager.GetString("ItemDataViewModel_ItemDisplayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name (TH).
        /// </summary>
        public static string ItemDataViewModel_ItemDisplayTH {
            get {
                return ResourceManager.GetString("ItemDataViewModel_ItemDisplayTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemDataViewModel_ItemName {
            get {
                return ResourceManager.GetString("ItemDataViewModel_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemDataViewModel_ItemTypeID {
            get {
                return ResourceManager.GetString("ItemDataViewModel_ItemTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string ItemDataViewModel_RequestType {
            get {
                return ResourceManager.GetString("ItemDataViewModel_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ItemDataViewModel_Status {
            get {
                return ResourceManager.GetString("ItemDataViewModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ItemStatus_Active {
            get {
                return ResourceManager.GetString("ItemStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string ItemStatus_Inactive {
            get {
                return ResourceManager.GetString("ItemStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewModel_Password {
            get {
                return ResourceManager.GetString("LoginViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay signed in.
        /// </summary>
        public static string LoginViewModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginViewModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginViewModel_Username {
            get {
                return ResourceManager.GetString("LoginViewModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string MiscStatus_Active {
            get {
                return ResourceManager.GetString("MiscStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string MiscStatus_Inactive {
            get {
                return ResourceManager.GetString("MiscStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string PhotoByType_Employee {
            get {
                return ResourceManager.GetString("PhotoByType_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsource.
        /// </summary>
        public static string PhotoByType_Outsource {
            get {
                return ResourceManager.GetString("PhotoByType_Outsource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReqApproverListViewModel_ApprovalCode {
            get {
                return ResourceManager.GetString("ReqApproverListViewModel_ApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string ReqApproverListViewModel_ApprovalDate {
            get {
                return ResourceManager.GetString("ReqApproverListViewModel_ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string ReqApproverListViewModel_RejectReason {
            get {
                return ResourceManager.GetString("ReqApproverListViewModel_RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string RoleViewModel_IsActive {
            get {
                return ResourceManager.GetString("RoleViewModel_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait to acknowledge.
        /// </summary>
        public static string WaitToAcknowledge_Status {
            get {
                return ResourceManager.GetString("WaitToAcknowledge_Status", resourceCulture);
            }
        }
    }
}
