//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiveReturnVisitorCardDataViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiveReturnVisitorCardDataViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.ReceiveReturnVisitorCardDataViewModelResource", typeof(ReceiveReturnVisitorCardDataViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_AreaName {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_CardID {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_CardNo {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date From.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date To.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_TimeIn {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_TimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Date.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_TimeOut {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify No..
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_VerifyNo {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_VerifyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_VerifyTypeID {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_VerifyTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Type.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_VerifyTypeName {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_VerifyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Name.
        /// </summary>
        public static string ReceiveReturnVisitorCardDataViewModel_VisitorName {
            get {
                return ResourceManager.GetString("ReceiveReturnVisitorCardDataViewModel_VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ReturnRetrieveVisitorCardDataViewModel_Company {
            get {
                return ResourceManager.GetString("ReturnRetrieveVisitorCardDataViewModel_Company", resourceCulture);
            }
        }
    }
}
