//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestDH08DataViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestDH08DataViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.RequestDH08DataViewModelResource", typeof(RequestDH08DataViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Area.
        /// </summary>
        public static string RequestDH08DataViewModel_Area {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string RequestDH08DataViewModel_DocumentType {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize Date From.
        /// </summary>
        public static string RequestDH08DataViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize Date To.
        /// </summary>
        public static string RequestDH08DataViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time From.
        /// </summary>
        public static string RequestDH08DataViewModel_EntryTimeFrom {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_EntryTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time To.
        /// </summary>
        public static string RequestDH08DataViewModel_EntryTimeTo {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_EntryTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipName.
        /// </summary>
        public static string RequestDH08DataViewModel_EquipName {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_EquipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string RequestDH08DataViewModel_ReqNo {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequestDH08DataViewModel_ReqStatus {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_ReqStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string RequestDH08DataViewModel_RequestBy {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_RequestBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDH08DataViewModel_RequestDate {
            get {
                return ResourceManager.GetString("RequestDH08DataViewModel_RequestDate", resourceCulture);
            }
        }
    }
}
