//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestDH06DataViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestDH06DataViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.RequestDH06DataViewModelResource", typeof(RequestDH06DataViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bringing Area.
        /// </summary>
        public static string RequestDH06DataViewModel_BringingArea {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_BringingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string RequestDH06DataViewModel_DocumentType {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize Date To.
        /// </summary>
        public static string RequestDH06DataViewModel_EntryDateTo {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_EntryDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time From.
        /// </summary>
        public static string RequestDH06DataViewModel_EntryTimeFrom {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_EntryTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time To.
        /// </summary>
        public static string RequestDH06DataViewModel_EntryTimeTo {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_EntryTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string RequestDH06DataViewModel_ReqNo {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_ReqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequestDH06DataViewModel_ReqStatus {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_ReqStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request By.
        /// </summary>
        public static string RequestDH06DataViewModel_RequestBy {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_RequestBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDH06DataViewModel_RequestDate {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Date.
        /// </summary>
        public static string RequestDH06DataViewModel_TakeInDate {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_TakeInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Name.
        /// </summary>
        public static string RequestDH06DataViewModel_TakeInName {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_TakeInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Company.
        /// </summary>
        public static string RequestDH06DataViewModel_TakeOutCompany {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_TakeOutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take In Department.
        /// </summary>
        public static string RequestDH06DataViewModel_TakeOutDepartment {
            get {
                return ResourceManager.GetString("RequestDH06DataViewModel_TakeOutDepartment", resourceCulture);
            }
        }
    }
}
