//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string Account_Profile_Title {
            get {
                return ResourceManager.GetString("Account_Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Acknowledge_Status_Title {
            get {
                return ResourceManager.GetString("Acknowledge_Status_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string AcsEmployee_BusinessTripSection_Title {
            get {
                return ResourceManager.GetString("AcsEmployee_BusinessTripSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string AcsEmployee_EmployeeListSection_Title {
            get {
                return ResourceManager.GetString("AcsEmployee_EmployeeListSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        public static string AcsEmployee_PopUpSection_EmployeeList_Add_Title {
            get {
                return ResourceManager.GetString("AcsEmployee_PopUpSection_EmployeeList_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Employee.
        /// </summary>
        public static string AcsEmployee_PopUpSection_Import_Title {
            get {
                return ResourceManager.GetString("AcsEmployee_PopUpSection_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Employee successfully..
        /// </summary>
        public static string AcsEmployee_PopUpSection_ImportSuccess {
            get {
                return ResourceManager.GetString("AcsEmployee_PopUpSection_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List is required.
        /// </summary>
        public static string AcsEmployeeDetailRequired {
            get {
                return ResourceManager.GetString("AcsEmployeeDetailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string AcsItemIn_ItemList_Title {
            get {
                return ResourceManager.GetString("AcsItemIn_ItemList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item In.
        /// </summary>
        public static string AcsItemIn_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("AcsItemIn_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item In.
        /// </summary>
        public static string AcsItemIn_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("AcsItemIn_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        public static string AcsItemOut_ItemList_Title {
            get {
                return ResourceManager.GetString("AcsItemOut_ItemList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item Out.
        /// </summary>
        public static string AcsItemOut_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("AcsItemOut_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item Out.
        /// </summary>
        public static string AcsItemOut_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("AcsItemOut_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List is required.
        /// </summary>
        public static string AcsItemOutDetailIsRequire {
            get {
                return ResourceManager.GetString("AcsItemOutDetailIsRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to GA.
        /// </summary>
        public static string AcsPhoto_GASection_Title {
            get {
                return ResourceManager.GetString("AcsPhoto_GASection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Employee must not be same Witness employee..
        /// </summary>
        public static string AcsPhoto_PhotoEmplyeeMustNotEqualWitnessEmployee {
            get {
                return ResourceManager.GetString("AcsPhoto_PhotoEmplyeeMustNotEqualWitnessEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest Request:.
        /// </summary>
        public static string AcsVIP_LatestRequest {
            get {
                return ResourceManager.GetString("AcsVIP_LatestRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Card Registration List.
        /// </summary>
        public static string AcsVIP_Title {
            get {
                return ResourceManager.GetString("AcsVIP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visitor.
        /// </summary>
        public static string AcsVisitor_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("AcsVisitor_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Visitor.
        /// </summary>
        public static string AcsVisitor_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("AcsVisitor_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Visitor.
        /// </summary>
        public static string AcsVisitor_PopUpSection_Import_Title {
            get {
                return ResourceManager.GetString("AcsVisitor_PopUpSection_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Visitor successfully..
        /// </summary>
        public static string AcsVisitor_PopUpSection_ImportSuccess {
            get {
                return ResourceManager.GetString("AcsVisitor_PopUpSection_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction List.
        /// </summary>
        public static string AcsVisitor_TransactionListSection_Title {
            get {
                return ResourceManager.GetString("AcsVisitor_TransactionListSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor List.
        /// </summary>
        public static string AcsVisitor_VisitorListSection_Title {
            get {
                return ResourceManager.GetString("AcsVisitor_VisitorListSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string ApprovalSection_Title {
            get {
                return ResourceManager.GetString("ApprovalSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string Area_AreaApprover_Approver_Title {
            get {
                return ResourceManager.GetString("Area_AreaApprover_Approver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituter 1.
        /// </summary>
        public static string Area_AreaApprover_Substituter1_Title {
            get {
                return ResourceManager.GetString("Area_AreaApprover_Substituter1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substituter 2.
        /// </summary>
        public static string Area_AreaApprover_Substituter2_Title {
            get {
                return ResourceManager.GetString("Area_AreaApprover_Substituter2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Area.
        /// </summary>
        public static string Area_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("Area_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Area_PopUpSection_AreaApprover_Department_Title {
            get {
                return ResourceManager.GetString("Area_PopUpSection_AreaApprover_Department_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Area_PopUpSection_AreaApprover_Position_Title {
            get {
                return ResourceManager.GetString("Area_PopUpSection_AreaApprover_Position_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Approver.
        /// </summary>
        public static string Area_PopUpSection_AreaApprover_Title {
            get {
                return ResourceManager.GetString("Area_PopUpSection_AreaApprover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Area.
        /// </summary>
        public static string Area_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("Area_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string Area_SearchSection_Factory {
            get {
                return ResourceManager.GetString("Area_SearchSection_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Area_SearchSection_Status {
            get {
                return ResourceManager.GetString("Area_SearchSection_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Mapping.
        /// </summary>
        public static string AreaMapping_Title {
            get {
                return ResourceManager.GetString("AreaMapping_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Code.
        /// </summary>
        public static string Asset_Code {
            get {
                return ResourceManager.GetString("Asset_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        public static string Card_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("Card_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string Card_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("Card_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File  .
        /// </summary>
        public static string Card_PopUpSection_Import_Title {
            get {
                return ResourceManager.GetString("Card_PopUpSection_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Card successfully..
        /// </summary>
        public static string Card_PopUpSection_ImportSuccess {
            get {
                return ResourceManager.GetString("Card_PopUpSection_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Employee Name.
        /// </summary>
        public static string CardRegistration_BusinessEmployeeName {
            get {
                return ResourceManager.GetString("CardRegistration_BusinessEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Trip Card Registration.
        /// </summary>
        public static string CardRegistration_BusinessTrip_Title {
            get {
                return ResourceManager.GetString("CardRegistration_BusinessTrip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string CardRegistration_Company {
            get {
                return ResourceManager.GetString("CardRegistration_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string CardRegistration_EntryDate {
            get {
                return ResourceManager.GetString("CardRegistration_EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card Type.
        /// </summary>
        public static string CardRegistration_RegisterCardType {
            get {
                return ResourceManager.GetString("CardRegistration_RegisterCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester Name.
        /// </summary>
        public static string CardRegistration_RequesterName {
            get {
                return ResourceManager.GetString("CardRegistration_RequesterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Visitor Card Registration.
        /// </summary>
        public static string CardRegistration_Visitor_PopupSection_Title {
            get {
                return ResourceManager.GetString("CardRegistration_Visitor_PopupSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seacrh Visitor Request.
        /// </summary>
        public static string CardRegistration_Visitor_SearchSection_Title {
            get {
                return ResourceManager.GetString("CardRegistration_Visitor_SearchSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Card Registration.
        /// </summary>
        public static string CardRegistration_Visitor_Title {
            get {
                return ResourceManager.GetString("CardRegistration_Visitor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Name.
        /// </summary>
        public static string CardRegistration_VisitorName {
            get {
                return ResourceManager.GetString("CardRegistration_VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Confdt_IsFalse {
            get {
                return ResourceManager.GetString("Confdt_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Confdt_IsTrue {
            get {
                return ResourceManager.GetString("Confdt_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmtion_Title {
            get {
                return ResourceManager.GetString("Confirmtion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item In Request waiting to Confirm Quantity.
        /// </summary>
        public static string Dashboard_ItemIn_Title {
            get {
                return ResourceManager.GetString("Dashboard_ItemIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Out Request waiting to Confirm Quantity.
        /// </summary>
        public static string Dashboard_ItemOut_Title {
            get {
                return ResourceManager.GetString("Dashboard_ItemOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request in Progress.
        /// </summary>
        public static string Dashboard_RequestInProgress_Title {
            get {
                return ResourceManager.GetString("Dashboard_RequestInProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request waiting to Approver.
        /// </summary>
        public static string Dashboard_RequestWaitingToApprover_Title {
            get {
                return ResourceManager.GetString("Dashboard_RequestWaitingToApprover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request waiting to Acknowledge.
        /// </summary>
        public static string Dashboard_RequestWaitToAcknowledge_Title {
            get {
                return ResourceManager.GetString("Dashboard_RequestWaitToAcknowledge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request waiting to Input Lending Information.
        /// </summary>
        public static string Dashboard_RequestWaitToInputLending_Title {
            get {
                return ResourceManager.GetString("Dashboard_RequestWaitToInputLending_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Room.
        /// </summary>
        public static string Dashboard_SecurityRoom_Title {
            get {
                return ResourceManager.GetString("Dashboard_SecurityRoom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Request.
        /// </summary>
        public static string Dashboard_WitnessRequest_Title {
            get {
                return ResourceManager.GetString("Dashboard_WitnessRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Inofrmation.
        /// </summary>
        public static string EmployeeEntry_Information_Title {
            get {
                return ResourceManager.GetString("EmployeeEntry_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total error {0} records.
        /// </summary>
        public static string ImportData_Error_Title {
            get {
                return ResourceManager.GetString("ImportData_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total data {0} records.
        /// </summary>
        public static string ImportData_Success_Title {
            get {
                return ResourceManager.GetString("ImportData_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        public static string InquiryEmployeeList_Title {
            get {
                return ResourceManager.GetString("InquiryEmployeeList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item Request.
        /// </summary>
        public static string Item_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("Item_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item Request.
        /// </summary>
        public static string Item_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("Item_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string Item_SearchSection_ItemName {
            get {
                return ResourceManager.GetString("Item_SearchSection_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemType.
        /// </summary>
        public static string Item_SearchSection_ItemType {
            get {
                return ResourceManager.GetString("Item_SearchSection_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string Item_SearchSection_RequestType {
            get {
                return ResourceManager.GetString("Item_SearchSection_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Item_SearchSection_Status {
            get {
                return ResourceManager.GetString("Item_SearchSection_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login_FormSection_Title {
            get {
                return ResourceManager.GetString("Login_FormSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        public static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous List.
        /// </summary>
        public static string Misc_GridSection_Title {
            get {
                return ResourceManager.GetString("Misc_GridSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Miscellaneous.
        /// </summary>
        public static string Misc_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("Misc_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Miscellaneous.
        /// </summary>
        public static string Misc_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("Misc_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Misc_SearchSection_MiscStatus {
            get {
                return ResourceManager.GetString("Misc_SearchSection_MiscStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Type.
        /// </summary>
        public static string Misc_SearchSection_MiscType {
            get {
                return ResourceManager.GetString("Misc_SearchSection_MiscType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteSection_Title {
            get {
                return ResourceManager.GetString("NoteSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Employee Name.
        /// </summary>
        public static string ReceiveReturn_BusinessEmployeeName {
            get {
                return ResourceManager.GetString("ReceiveReturn_BusinessEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ReceiveReturn_BusinessTrip_PopupSection_Title {
            get {
                return ResourceManager.GetString("ReceiveReturn_BusinessTrip_PopupSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Trip Card Registration.
        /// </summary>
        public static string ReceiveReturn_BusinessTrip_Title {
            get {
                return ResourceManager.GetString("ReceiveReturn_BusinessTrip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string ReceiveReturn_Company {
            get {
                return ResourceManager.GetString("ReceiveReturn_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string ReceiveReturn_EntryDate {
            get {
                return ResourceManager.GetString("ReceiveReturn_EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string ReceiveReturn_Factory {
            get {
                return ResourceManager.GetString("ReceiveReturn_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card Type.
        /// </summary>
        public static string ReceiveReturn_RegisterCardType {
            get {
                return ResourceManager.GetString("ReceiveReturn_RegisterCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Name.
        /// </summary>
        public static string ReceiveReturn_RequesterName {
            get {
                return ResourceManager.GetString("ReceiveReturn_RequesterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ReceiveReturn_Visitor_PopupSection_Title {
            get {
                return ResourceManager.GetString("ReceiveReturn_Visitor_PopupSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Card Registration.
        /// </summary>
        public static string ReceiveReturn_Visitor_Title {
            get {
                return ResourceManager.GetString("ReceiveReturn_Visitor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Name.
        /// </summary>
        public static string ReceiveReturn_VisitorName {
            get {
                return ResourceManager.GetString("ReceiveReturn_VisitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestList.
        /// </summary>
        public static string RequestInquriy_RequestList_Title {
            get {
                return ResourceManager.GetString("RequestInquriy_RequestList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only upload &lt;strong&gt;{0}&lt;/strong&gt; files. Maximum allowed upload file size is &lt;strong&gt;{1}&lt;/strong&gt;..
        /// </summary>
        public static string UploadHint {
            get {
                return ResourceManager.GetString("UploadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role List.
        /// </summary>
        public static string UserGroup_ListSection_Title {
            get {
                return ResourceManager.GetString("UserGroup_ListSection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Group.
        /// </summary>
        public static string UserGroup_PopUpSection_Add_Title {
            get {
                return ResourceManager.GetString("UserGroup_PopUpSection_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Group.
        /// </summary>
        public static string UserGroup_PopUpSection_Edit_Title {
            get {
                return ResourceManager.GetString("UserGroup_PopUpSection_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string UserGroup_Title {
            get {
                return ResourceManager.GetString("UserGroup_Title", resourceCulture);
            }
        }
    }
}
