//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VIPCardRegistrationViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VIPCardRegistrationViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.VIPCardRegistrationViewModelResource", typeof(VIPCardRegistrationViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string VIPCardRegistrationViewModel_Area {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID.
        /// </summary>
        public static string VIPCardRegistrationViewModel_CardID {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_CardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No..
        /// </summary>
        public static string VIPCardRegistrationViewModel_CardNo {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string VIPCardRegistrationViewModel_Company {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string VIPCardRegistrationViewModel_Description {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date From.
        /// </summary>
        public static string VIPCardRegistrationViewModel_EntryDateFrom {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_EntryDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VIPCardRegistrationViewModel_Name {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string VIPCardRegistrationViewModel_PositionID {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_PositionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Name.
        /// </summary>
        public static string VIPCardRegistrationViewModel_PositionName {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No..
        /// </summary>
        public static string VIPCardRegistrationViewModel_RequestNo {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string VIPCardRegistrationViewModel_SelectedAreaList {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_SelectedAreaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string VIPCardRegistrationViewModel_Status {
            get {
                return ResourceManager.GetString("VIPCardRegistrationViewModel_Status", resourceCulture);
            }
        }
    }
}
