//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECOM.ACS.MvcWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WidgetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WidgetResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SECOM.ACS.MvcWebApp.Resources.WidgetResource", typeof(WidgetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - All -.
        /// </summary>
        public static string AllOptions {
            get {
                return ResourceManager.GetString("AllOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string Button_Account_Text {
            get {
                return ResourceManager.GetString("Button_Account_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string Button_Acknowlege_Text {
            get {
                return ResourceManager.GetString("Button_Acknowlege_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add_Text {
            get {
                return ResourceManager.GetString("Button_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add_Title {
            get {
                return ResourceManager.GetString("Button_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Button_Approve_Text {
            get {
                return ResourceManager.GetString("Button_Approve_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting.
        /// </summary>
        public static string Button_Busy_Text {
            get {
                return ResourceManager.GetString("Button_Busy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel_Text {
            get {
                return ResourceManager.GetString("Button_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Request.
        /// </summary>
        public static string Button_CancelRequest_Text {
            get {
                return ResourceManager.GetString("Button_CancelRequest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear_Text {
            get {
                return ResourceManager.GetString("Button_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear_Title {
            get {
                return ResourceManager.GetString("Button_Clear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close_Text {
            get {
                return ResourceManager.GetString("Button_Close_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Button_Copy_Text {
            get {
                return ResourceManager.GetString("Button_Copy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete_Text {
            get {
                return ResourceManager.GetString("Button_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete_Title {
            get {
                return ResourceManager.GetString("Button_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Button_Duplicate_Text {
            get {
                return ResourceManager.GetString("Button_Duplicate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit_Text {
            get {
                return ResourceManager.GetString("Button_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit_Title {
            get {
                return ResourceManager.GetString("Button_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File.
        /// </summary>
        public static string Button_Export_Text {
            get {
                return ResourceManager.GetString("Button_Export_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Done.
        /// </summary>
        public static string Button_ForceDone_Text {
            get {
                return ResourceManager.GetString("Button_ForceDone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import_Text {
            get {
                return ResourceManager.GetString("Button_Import_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Button_Receive_Text {
            get {
                return ResourceManager.GetString("Button_Receive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh_Text {
            get {
                return ResourceManager.GetString("Button_Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Button_Reject_Text {
            get {
                return ResourceManager.GetString("Button_Reject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Button_Reset_Text {
            get {
                return ResourceManager.GetString("Button_Reset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Button_Reset_Title {
            get {
                return ResourceManager.GetString("Button_Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Button_ResetPassword_Text {
            get {
                return ResourceManager.GetString("Button_ResetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        public static string Button_Retrieve_Text {
            get {
                return ResourceManager.GetString("Button_Retrieve_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Button_Return_Text {
            get {
                return ResourceManager.GetString("Button_Return_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save_Text {
            get {
                return ResourceManager.GetString("Button_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_Text {
            get {
                return ResourceManager.GetString("Button_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_Title {
            get {
                return ResourceManager.GetString("Button_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Button_Sigin_Text {
            get {
                return ResourceManager.GetString("Button_Sigin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update_Text {
            get {
                return ResourceManager.GetString("Button_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Button_View_Text {
            get {
                return ResourceManager.GetString("Button_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        public static string Button_ViewMap_Text {
            get {
                return ResourceManager.GetString("Button_ViewMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Button_Text {
            get {
                return ResourceManager.GetString("ChangePassword_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Equal To.
        /// </summary>
        public static string Filter_Operator_IsEqualTo {
            get {
                return ResourceManager.GetString("Filter_Operator_IsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Grid_Column_No {
            get {
                return ResourceManager.GetString("Grid_Column_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Grid_Status_Text {
            get {
                return ResourceManager.GetString("Grid_Status_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Clear -.
        /// </summary>
        public static string List_ClearOptions {
            get {
                return ResourceManager.GetString("List_ClearOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string List_NA_Options {
            get {
                return ResourceManager.GetString("List_NA_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select -.
        /// </summary>
        public static string SelectOptions {
            get {
                return ResourceManager.GetString("SelectOptions", resourceCulture);
            }
        }
    }
}
